# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  
  # Configure AWS
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAJV6CBJ5RFBNSIE7Q"
    aws.secret_access_key = "UOHGFG6IAO4QXYjfbQHQysSmmFNqx16jnv8MbSvw"
    aws.region = "eu-central-1"
    aws.instance_type = "t2.micro"
    aws.keypair_name = "AWSUbuntu"
    security_groups = ["default"]
    aws.ami = "ami-accff2b1"
    # Configure ssh
    override.ssh.private_key_path = "/Users/ProZsolt/Desktop/Cheppers/keys/AWSUbuntu.pem"
    override.ssh.username = "ubuntu"
  end
  
  # install Puppet
  config.vm.provision "shell", :inline => <<-SHELL
    apt-get update
    apt-get install -y puppet
  SHELL

  # Configure Puppet apply
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "/Users/ProZsolt/Desktop/Cheppers/puppet/manifests"
    puppet.module_path = "/Users/ProZsolt/Desktop/Cheppers/puppet/modules"
    puppet.manifest_file  = "site.pp"
  end
end
